export const AUTH_CONSTANTS = {
    ACCESS_TOKEN_EXPIRY: '15m',
    REFRESH_TOKEN_EXPIRY: '7d',
    RESET_TOKEN_EXPIRY: '1h',
    VERIFICATION_TOKEN_EXPIRY: '24h',
    MAX_LOGIN_ATTEMPTS: 5,
    LOCKOUT_TIME: 30 * 60 * 1000 // 30 minutes
};